services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=lanternflyaway
    restart: unless-stopped

volumes:
  mongodb_data: